"""Rebuild the ``submission`` branch as "current HEAD minus .submission-exclude".

Why a branch and not just the bundle
------------------------------------
Anonymous GitHub proxies a *real branch* rather than a prepared archive, so
anything present on the branch it points at is served to reviewers. The bundle
directory is therefore not enough: the exclusions have to exist as a commit.

Why regenerate rather than patch
-------------------------------
The branch is a pure function of ``HEAD`` and the exclude list, so it is rebuilt
from scratch each time. Merging development commits into it instead would leave
the two histories to diverge and make "what is actually in the submission?"
a question you have to reason about rather than recompute.

The rebuild is local only. Publishing it needs a force push, because the branch
is rewritten by design::

    git push --force-with-lease origin submission

Usage::

    python tools/refresh_submission_branch.py            # rebuild + verify
    python tools/refresh_submission_branch.py --no-tests # skip the test run
"""

from __future__ import annotations

import argparse
import fnmatch
import subprocess
import sys
from pathlib import Path

BRANCH = "submission"
EXCLUDE_FILE = ".submission-exclude"


def git(*args: str, check: bool = True) -> str:
    proc = subprocess.run(("git", *args), capture_output=True, text=True)
    if check and proc.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} failed:\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def load_patterns() -> list[str]:
    lines = Path(EXCLUDE_FILE).read_text().splitlines()
    return [p for p in (l.split("#", 1)[0].strip() for l in lines) if p]


def matches(rel: str, patterns: list[str]) -> bool:
    for pat in patterns:
        if pat.endswith("/"):
            if rel.startswith(pat):
                return True
        elif fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(Path(rel).name, pat):
            return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--no-tests", action="store_true",
                    help="Skip running the branch's test suite after rebuilding.")
    args = ap.parse_args()

    if git("status", "--porcelain", "--untracked-files=no"):
        raise SystemExit("working tree has uncommitted tracked changes; commit or "
                         "stash them first so the branch is reproducible")

    source = git("rev-parse", "--abbrev-ref", "HEAD")
    if source == BRANCH:
        raise SystemExit(f"currently on {BRANCH}; switch to the development branch")
    head = git("rev-parse", "--short", "HEAD")
    patterns = load_patterns()

    git("checkout", "-q", "-B", BRANCH)
    try:
        tracked = git("ls-files").split("\n")
        drop = [r for r in tracked if r and matches(r, patterns)]
        if not drop:
            raise SystemExit("exclude list matched nothing -- check .submission-exclude")
        git("rm", "-q", "--", *drop)
        git("commit", "-q", "-m",
            f"Submission tree: {source}@{head} minus {len(drop)} excluded path(s)\n\n"
            "Regenerated by tools/refresh_submission_branch.py. The branch is a\n"
            "pure function of HEAD and .submission-exclude, so it is rebuilt rather\n"
            "than merged into: an Anonymous GitHub proxy serves whichever branch it\n"
            "points at, and a divergent history would make the contents of the\n"
            "submission something to reason about instead of recompute.\n\n"
            "Excluded: deployment and diagnostics tooling plus the anonymisation\n"
            "scripts. No evaluation code is removed; every reported number is still\n"
            "reproducible from this tree.")
        print(f"{BRANCH} rebuilt from {source}@{head}: "
              f"{len(tracked) - len(drop)} kept, {len(drop)} excluded")
        for r in drop:
            print(f"   -{r}")

        if not args.no_tests:
            print("\nrunning the branch's test suite...")
            proc = subprocess.run(
                [sys.executable, "-m", "pytest", "ocm/tests", "-q",
                 "-p", "no:cacheprovider"],
                capture_output=True, text=True)
            tail = [l for l in proc.stdout.splitlines() if l.strip()][-3:]
            print("\n".join(f"  {l}" for l in tail))
            if proc.returncode != 0:
                print("\nFAILED: an exclusion removed something load-bearing",
                      file=sys.stderr)
                return 1
    finally:
        git("checkout", "-q", source)
        print(f"\nback on {source}; publish with:\n"
              f"  git push --force-with-lease origin {BRANCH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
